### ISSUE TITLE
preview

### ISSUE THREAD

**Issue by natxopedreira** [Otaze/RekkonMMALCamera#1]
Hello

I just found your great mmal wrapper, thank you!!! and i would like to use it to do a simple app.

Im not able to get a preview and no errors on console, im doing something like.. but i get no preview:

Im doing something wrong?

```
RekkonCamControl camera;
camera.open();
camera.setStillPreviewSize(1280,720);
camera.startStillPreview();
```

**Comment by Otaze** [comment]
Hello,
The start function doesn't display any image by itself. Once the preview is started, the buffer will be updated each time the camera pipeline is processed. You have to grab the image in the buffer and retrieve it. Here is how I do it :
```
            if (m_cam_control.grab())
            {
                if (m_cam_control.isVideoPreviewOpened())
                    m_frame->create(m_cam_control.getVideoPreviewHeight(), m_cam_control.getVideoPreviewWidth(), CV_8UC3);
                else m_frame->create(m_cam_control.getStillPreviewHeight(), m_cam_control.getStillPreviewWidth(), CV_8UC3);

                m_cam_control.retrieve(m_frame->ptr<uchar> ( 0 ));
            }
```
I use an opencv mat (m_frame) as opencv is a library that has display functions.

**Comment by natxopedreira** [comment]
Hello

Ok, i understand, sounds great!!

Thank you
