### ISSUE TITLE
encoder_buffer_callback

### ISSUE THREAD

**Issue by natxopedreira** [Otaze/RekkonMMALCamera#2]
Hello

Sorry to disturb, im using part of your class in a openframeworks addon and works nice, did some mods and set to use dual camera nothing important

Now i want to change that when taking a photo i can grab the "pixels" instead of creating a file. If you don't mind have some questions.

+ why encoder_buffer_callback is called more than once when taking a still (full res)

+ i found first time call take still i get a 0 byte file... the next ones are ok but first is almost always 0, is expected behavior¿?

Thank you so much, class works great

**Comment by Otaze** [comment]
Hello,
Glad it works well for you.
encoder_buffer_callback is a function sent as a parameter to the mmal lib encoder. 
If I recall correctly, the encoder can call the function with a buffer that can have multiple signification according to its flag (encoding in progress, encoding end, encoding fail etc...) .
So it might be normal to have multiple calls to encoder_buffer_callback.
But for the file with 0 byte, I don't think it's to be expected. I shall look further into it when I have a bit of time.

**Comment by natxopedreira** [comment]
Thanks for the answer, i understand.

Did you know if is possible to get the data uncompressed like the preview buffer i tried changing the encoding parameter to rgb but crashed creating the component, right now i need to "decompress" jpg data and is wasting resources

**Comment by Otaze** [comment]
I guess that if you remove the encoder step in the pipeline, you configure the image output port so that it's similar to the still preview output port and you connect it to a callback function similar to preview_buffer_callback, you would be able to copy pixels from the buffer.

**Comment by natxopedreira** [comment]
Thanks!
